version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tg_postgres
    restart: always
    environment:
      POSTGRES_DB: tgdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Kyiv
      PGTZ: Europe/Kyiv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tg-controller-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/tgdb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      TELEGRAM_BOT_TOKEN: 8311135414:AAGGjH2Btopbi2FOl5w2DI87yY4CDcIKbaY
    ports:
      - "8282:8282"
    restart: always

volumes:
  postgres_data:
