spring:
  jackson:
    time-zone: Europe/Kyiv
  application:
    name: learn-tg-bot
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/tgdb
#    url: r2dbc:postgresql://localhost:5432/tgdb
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
    properties:
      options:
        timezone: Europe/Kyiv

telegram:
  bot:
    token: 8311135414:AAGGjH2Btopbi2FOl5w2DI87yY4CDcIKbaY
    username: cursor_sobaka_bot

logging:
  level:
    root: info

server:
  port: 8282

url:
  socket: http://tg-controller-socket:8484/
  telegram: https://api.telegram.org/bot